version: 0.2
# Defining default values for all jobs
defaults: &defaults
  docker:
    - image: abhisheksaxena7/salesforcedockerimg
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `14/05/2020`
      - echo master Branch Script Called...
      - echo $SFDC_USERNAME
      - echo $SFDC_PASSWORD
      - echo $SFDC_TOKEN
      - echo $SFDC_SERVERURL
      - ant -buildfile build/build.xml deployEmptyCheckOnly -Dsfdc.username=$SFDC_USERNAME -Dsfdc.password=$SFDC_PASSWORD$SFDC_TOKEN -Dsfdc.serverurl=https://$SFDC_SERVERURL
  post_build:
    commands:
      - echo Build completed on `14/05/2020`
artifacts:
  files:
    - target/messageUtil-1.0.jar
